---
title: "sensitivity"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(sensitivity)
library(tidyverse)
library(pse)

```

## Example of using LHS for sensitivity analysis

Make sure you install the **pse** library


Lets look at our almond yield example

```{r almondsens}

# for formal sensitivity analysis it is useful to describe output in
# several summary statistics - how about mean, max and min yield
source("./compute_almond_yield.R")


# Lets consider 3 of the parameters....
factors = c("Tmincoeff1", "Tmincoeff2", "Pcoeff2")

# Decide How many parameter sets to run
nsets=100

# choose distributions for parameters - this would come from
# what you know about the likely range of variation
q = c("qnorm", "qnorm", "qunif")
q.arg = list(list(mean=,sd=0.005), list(mean=-0.0046, sd=0.001), list(min=0.00429, max=0.00431))

# generate samples from LHS
sens_almond = LHS(NULL,factors,nsets,q,q.arg)
sens_pars = get.data(sens_almond)
head(sens_pars)


# read in the input data
SB=read.table("./clim.txt")
colnames(SB) <- SB[1,]
SB = SB[-1, ]
clim= SB



# lets now run our model for all of the parameters generated by LHS
# pmap is useful here - it is a map function that uses the actual names of input parameters

res = sens_pars %>% pmap(compute_almond_yield,clim=clim)

# notice that what pmap returns is a list 
head(res)

# turn results in to a dataframe for easy display/analysis
resd = res %>% map_dfr(`[`,c("maxyield","minyield","meanyield"))

# to take advantage of LHS/pse functions for plotting interesting information we can send results back - results need to be in a matrix
# each column is a different parameter set - we can use transpose (t)
# and as.matrix to get there

# tell is what links output to original LHS object

sens_almond = pse::tell(sens_almond, t(as.matrix(resd)), res.names=c("maxyield","minyield","meanyield"))

# now we use built in LHS functions to analyze parameter seneisitiy
pse::plotscatter(sens_almond, col="blue", cex=5)

# prcc's automatically generated and easy to plot
pse::plotprcc(sens_almond)
sens_almond$prcc

# we can also plot results in interesting ways
# turn sens_results into a data frame - easier access to R plotting functions


ggplot(resd, aes(minyield, maxyield))+geom_point()+labs(y="Max Yield (as anomoly)", "Min Yield (as anomoly")


# add uncertainty bounds on our estimates
tmp = resd %>% gather(value="value", key="yield")
ggplot(tmp, aes(yield, value, col=yield))+geom_boxplot()+labs(y="Yield (as anomoly)")

# note that you don't see the ranges because of the scale (min yield anomoly much smaller than max) - here's a more informative way to graph
ggplot(tmp, aes(yield, value, col=yield))+geom_boxplot()+labs(y="Yield (as anomoly)")+facet_wrap(~yield, scales="free" )




```

