---
title: "Assignemnt 6"
author: "Ruben Sanchez Ramirez, Madeline Oliver, Atefeh Mohseni"
date: "May 9, 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

```

```{r}

# Attach packages:
library(tidyverse)
library(deSolve)
library(sensitivity)
library(ggplot2)

```

```{r}

# call the function
source("./R/forest_growth.R")

```

```{r}

# set parameters
years = seq(from=1, to=300, by=1)
initial_C = 10
thresh = 50
K = 250
r = 0.01
g = 2

# create parameter list
parms = list(thresh = thresh, K=K, r=r, g=g)

# run ODE solver for the equation using the given parameters
result = ode(y=initial_C, time=years, func=forest_growth, parms=parms)

# change the column names
colnames(result)=c("year","C")
# view the results
head(result)
# turn it into a data frame
result = as.data.frame(result)

```

```{r}

# Plot the results:
plot.a6.1 <- result %>% 
  ggplot(aes(year, C))+
  geom_point()+
  theme_classic()+
  labs(x = "Years",
       y = "Forest Size in Units of Carbon (C)") +
  theme(text = element_text(family = "serif"),
        axis.title.x = element_text(size=12, face="bold"),
        axis.title.y = element_text(size=12, face="bold"),
        axis.text.x = element_text(size=8),
        axis.text.y = element_text(size=8))

# call the plot
plot.a6.1

```

```{r}

# Run a sobol sensitivity analysis that explores how the estimated maximum and mean forest size varies with r, g, and K:

# come up with first set of sample parameters
# we will assume that we know the initial forest size in carbon (C)
initial_C = 10

# lets start with sobel 
# want to learn about sensitivity to growth rate (r), post-canopy growth rate (g), and carrying capacity (K):
# set the number of parameters
np=100
r = rnorm(mean=0.01, sd=0.01*0.1, n=np)
g = rnorm(mean=2, sd=2*0.1, n=np)
thresh = rnorm(mean=50, sd=50*0.1, n=np)
K = rnorm(mean=250, sd=250*0.1, n=np)
X1 = cbind.data.frame(r=r, g=g, thresh=thresh, K=K)

# repeat to get our second set of samples
r = rnorm(mean=0.01, sd=0.01*0.1, n=np)
g = rnorm(mean=2, sd=2*0.1, n=np)
thresh = rnorm(mean=50, sd=50*0.1, n=np)
K = rnorm(mean=250, sd=250*0.1, n=np)
X2 = cbind.data.frame(r=r, g=g, thresh=thresh, K=K)

# create our sobel object and get sets of parameters for running the model
sens_P = soboljansen(model = NULL,X1, X2, nboot = 300)

# our parameter sets are
head(sens_P$X)

# for illustration lets look at running just one parameter sets and summarizing results
sens_P$X[1,]
# recall ODE needs ALL of our parameters in a single list 
# initial population and timnes for which we want output 
initial_C
# gets results for 300 years (evaluating every year)
simtimes = seq(from=1, to=300)
parms = list(r=sens_P$X$r[1], thresh=sens_P$X$thresh[1], g=sens_P$X$g[1], K=sens_P$X$K[1])
result = ode(y=initial_C, times=simtimes, func=forest_growth, parms=parms)
head(result)
colnames(result)=c("time","C")
# turn it into a data frame
result = as.data.frame(result)
ggplot(result, aes(time, C))+geom_point()
# extra our metrics of interest  from this
# maximum population it gets to
max_C = max(result$C)
mean_C = mean(result$C)

```

```{r}

# turn computing our metrics into a function
compute_metrics = function(result) {
  max_C = max(result$C)
  mean_C = mean(result$C)
return(list(max_C=max_C, mean_C=mean_C))}

# try it on our first parameter set
compute_metrics(result)

# define a wrapper function to do everything we need - run solver and compute metrics - and send back results for each parameter
p_wrapper = function(r,g, thresh, K, initial_C, simtimes, func) {
    parms = list(r=r, g=g, thresh=thresh, K=K)
    result = ode(y=initial_C, times=simtimes, func=forest_growth, parms=parms) 
    colnames(result)=c("time","C")
  # get metrics
  metrics=compute_metrics(as.data.frame(result))
  return(metrics)
}

# now use pmap with the given single row values
allresults = sens_P$X %>% pmap(p_wrapper, initial_C=initial_C, simtimes=simtimes, func=forest_growth())

# extract out results from pmap into a data frame
allres = allresults %>% map_dfr(`[`,c("max_C","mean_C"))

# create boxplots
tmp = allres %>% gather(key="metric", value="value")
ggplot(tmp, aes(metric, value, col=metric))+geom_boxplot()

```

```{r}

# sobol can only handle one output at a time  - do them separately
sens_P_maxC = sensitivity::tell(sens_P,allres$max_C)
# first-order (main effect without co-variance)
sens_P_maxC$S
# total sensitivity index
sens_P_maxC$T
plot(sens_P_maxC)
# create another one for mean
sens_P_meanC = sensitivity::tell(sens_P,allres$mean_C)
# first-order (main effect without co-variance)
sens_P_meanC$S
# total sensitivity index
sens_P_meanC$T
plot(sens_P_meanC)

```


